### ISSUE TITLE
真正的渣渣求建议

### ISSUE THREAD

**Issue by noahlam** [yujiangshui/A-Programmers-Guide-to-English#10]
这2年也一直在学英语，不过仅局限在背单词上，从刚开始1000左右的词汇量，背到现在差不多有6-7000，感觉阅读是有明显的进步了，听力的话，专注一点，也能听一些不是很难的，但是对于语法，是完全不懂，以前学生时代，根本就没学过英文，现在语法也不知道从何学起，目前“说”跟“写”还是0的状态，有什么好的建议吗？

**Comment by lanxkk** [comment]
英语流利说的《懂你英语》对“听”和“说”的帮助还是蛮大的。

**Comment by yujiangshui** [comment]
说跟写不行，可能缺乏锻炼。说的方面先按照文章从音标开始，再到纠音，再到读段落，先把基础搞一搞，然后做跟读和复述。写的话可以参照文章中恶魔的奶爸那个写作教程，来做转述训练试试。

语法我本身也不好，目前是找了一些带习题的剑桥出的语法书在做，还没做完不做推荐了。

个人感觉你的关键还是要找个需求，没需求的话只是自己苦练，需要意志力比较大。比如有出国需求或者与国外交流的需求或者在外企工作。这样有需求也有场景训练，提升比较好。

**Comment by fooski** [comment]
强烈建议使用Tandem或者其他语言交换服务来跟英语母语者聊天，英语这个语感是非常重要的，单词你倒是可以死记硬背，但是语法这个东西你必须得说才能记住

**Comment by tonghua209** [comment]
取个英国或者美国妹子，凑合一下南非或者印度也可以。

**Comment by noahlam** [comment]
> 取个英国或者美国妹子，凑合一下南非或者印度也可以。

已经娶了个英文比我还差的。。。回不了头了哈

**Comment by noahlam** [comment]
> 说跟写不行，可能缺乏锻炼。说的方面先按照文章从音标开始，再到纠音，再到读段落，先把基础搞一搞，然后做跟读和复述。写的话可以参照文章中恶魔的奶爸那个写作教程，来做转述训练试试。
> 
> 语法我本身也不好，目前是找了一些带习题的剑桥出的语法书在做，还没做完不做推荐了。
> 
> 个人感觉你的关键还是要找个需求，没需求的话只是自己苦练，需要意志力比较大。比如有出国需求或者与国外交流的需求或者在外企工作。这样有需求也有场景训练，提升比较好。

我目前最主要的需求，就是能看得懂技术文档而已，出国跟留学暂时都没有打算哈。

**Comment by gongwenqiang** [comment]
> > 说跟写不行，可能缺乏锻炼。说的方面先按照文章从音标开始，再到纠音，再到读段落，先把基础搞一搞，然后做跟读和复述。写的话可以参照文章中恶魔的奶爸那个写作教程，来做转述训练试试。
> > 语法我本身也不好，目前是找了一些带习题的剑桥出的语法书在做，还没做完不做推荐了。
> > 个人感觉你的关键还是要找个需求，没需求的话只是自己苦练，需要意志力比较大。比如有出国需求或者与国外交流的需求或者在外企工作。这样有需求也有场景训练，提升比较好。
> 
> 我目前最主要的需求，就是能看得懂技术文档而已，出国跟留学暂时都没有打算哈。
> 
> 所以....说跟写，是比较难咯？ 上面其他几位热心网友的建议我觉得还不错，先交几个外国朋友？

跟你有一样的需求，主要是看技术文档和国外技术视频。 训练的话，我觉得有还是这个环境，最好是老外，是在不行也可以找这方面牛逼点的。

**Comment by yujiangshui** [comment]
@gongwenqiang 正解
