### ISSUE TITLE
关于只查英英词典的问题

### ISSUE THREAD

**Issue by ynot12138** [yujiangshui/A-Programmers-Guide-to-English#16]
仅是补充：
原文作者也提示到了“尽量查英英词典”，但是可能会有一些读者没注意到——有些特殊情况：比如heron，中文“ 鹭”，但是要是这时仅查英英字典时，解释为“A large fish-eating wading bird with long legs, a long S-shaped neck, and a long pointed bill.”。
所以显然，对于此类型的特殊一点的词，只看英英释义会走向歧路啊。只是建议，欢迎讨论。

**Comment by yujiangshui** [comment]
我觉得你”认为走向歧路“的这个想法其实走向了歧路，当你看到 heron 这个单词，你还是希望先能想起来这是中文的 鹭 然后进而查询中文语料库想到是一种腿长的鸟，其实应该是看到 heron 就知道这是一个专属名词，表示一种 bird with long legs。

实际上还有很多专属或者当地自造的物品名称是根本没法翻译成中文的，遇到这种只有当地语言的释义。

**Comment by TellH** [comment]
> 我觉得你”认为走向歧路“的这个想法其实走向了歧路，当你看到 heron 这个单词，你还是希望先能想起来这是中文的 鹭 然后进而查询中文语料库想到是一种腿长的鸟，其实应该是看到 heron 就知道这是一个专属名词，表示一种 bird with long legs。
> 
> 实际上还有很多专属或者当地自造的物品名称是根本没法翻译成中文的，遇到这种只有当地语言的释义。

其实他的意思应该是，看了heron的英英解析后，不知道其实就是中文里的“ 鹭”，如果之后看到“ 鹭”后，没法联想出英语的heron

**Comment by ynot12138** [comment]
> 我觉得你”认为走向歧路“的这个想法其实走向了歧路，当你看到 heron 这个单词，你还是希望先能想起来这是中文的 鹭 然后进而查询中文语料库想到是一种腿长的鸟，其实应该是看到 heron 就知道这是一个专属名词，表示一种 bird with long legs。
> 
> 实际上还有很多专属或者当地自造的物品名称是根本没法翻译成中文的，遇到这种只有当地语言的释义。

可能朋友你误会了我的意思，我的意思是同**@TellH** 一样：“看了heron的英英解析后，不知道其实就是中文里的‘鹭’”。而不是
>当你看到 heron 这个单词，你还是希望先能想起来这是中文的 鹭 然后进而查询中文语料库想到是一种腿长的鸟，其实应该是看到 heron 就知道这是一个专属名词，表示一种 bird with long legs。
朋友你可能误会我是为了找毛病而找毛病，但真实意图是：我们在阅读英文的时候，看到了heron这个单词，此时我要执行”查英英字典“的操作。执行结果是，看到了不知所云的一大片诸如”A large fish-eating wading bird with long legs, a long S-shaped neck, and a long pointed bill.“ 的关于”bird“的**模糊描述**，而这时要是正好需要确定heron这个词”是何种bird“，这时没有办法了啊。（不需要准确确定的情况另当别论）
总的来说，在”做英文阅读“时，遇见生词，查英英字典，遇见了问题（仅有模糊描述）；而不是我为了找毛病而去专门想出一个词来责难你。

题外话，朋友我没有恶意，我也很喜欢你写的构建识别程序的章节；而且关于“只查英英字典”这件事我原来也是和你想的一样——“我就以后只查英英了，虽然对我自己开始时有些难，但是这样是‘纯英文语境’下学习，效果肯定好”。而当我有一天，看到了类似于一些特殊的专有名词其实不适合**只**查英英字典时，我也是很震惊的。而到朋友你这来评论，也是好意，没有恶意挑毛病的意思，还请理解。

**Comment by yujiangshui** [comment]
我其实没觉得你有恶意，如果我的语言让你感觉到了冒犯，先说声抱歉，我可能说得不够委婉比较直接 😊

我是从老外的角度来看这个事情，比如你后续补充的这个：

> 我们在阅读英文的时候，看到了heron这个单词，此时我要执行”查英英字典“的操作。执行结果是，看到了不知所云的一大片诸如”A large fish-eating wading bird with long legs, a long S-shaped neck, and a long pointed bill.“ 的关于”bird“的模糊描述，而这时要是正好需要确定heron这个词”是何种bird“，这时没有办法了啊。（不需要准确确定的情况另当别论）

通过这个描述你只能获取关于一种 bird 的模糊描述，对于老外也是这样的（实际我看到 鹭 也不知道具体什么样），如果你需要确定 heron 是何种 bird 时，对于老外可能会搜 youtube 看视频、搜 google 图片看形状、搜 wiki 看最详细的说明，而不是搜中文发现这是“鹭”。当然这只是日常交流使用层面，我个人觉得无法建立 `heron = 鹭` 的映射是没有问题的。

如果你想表达 @TellH 提到的这种情况，这种问题也是存在的，如果有汉英互译的需求，专属名词查询汉英词典可能比自己去找 heron 图片再对照中文的鸟图片发现是 鹭 准确、快捷的多，这个的确是要查汉英词典。

我最早看到你的描述，误认为你是想通过 heron 查询到 鹭，再通过自己对 鹭 的了解来认识 heron 这个单词，所以产出了上面那个回复。

**Comment by ynot12138** [comment]
哈哈哈，是的朋友，从你的讨论中我有了新的收获和启发，我需要重新思考这个问题，在此说声谢谢！（我在最早的问题中没有对“汉→英”这个方向的疑问，可能 @TellH 朋友的后半句对“汉→英”这个方向误会了我的意思（但他对“英→汉”的想法和我一致） ）
题外话，我们的讨论让我想起来之前看过一些二语习得理论的L1、L2、Concept、Lemma和Lexeme这些概念，你对这些的理解很不错的！

**Comment by yujiangshui** [comment]
好的。其实这种现象在编程领域非常常见，很多概念是没有权威中译的，有人写文章用英文，有人自己翻译中文而且不加英文原名导致对应不上英文版本，看起来也是很痛苦，想表达的概念不知道英文表达方法。目前对于这种情况，我在从初级技术教程快速刷，来熟悉下英文版本的相关概念并积累下来。
