### ISSUE TITLE
与众不同

### ISSUE THREAD

**Issue by jiahe224** [yujiangshui/A-Programmers-Guide-to-English#17]
一般的经验贴好像除了阐述自己的方法外，还会提到一些用到的资料，比如最最常见的新概念之类的，然后语法书什么的，这篇主要是告诉你权威，发音去哪纠正，单词怎么背等等，然后看完我继续看薄冰语法了
(lll￢ω￢)

**Comment by yujiangshui** [comment]
互为补充吧
