### ISSUE TITLE
找适合自己的i+1的跟读材料不容易啊

### ISSUE THREAD

**Issue by TellH** [yujiangshui/A-Programmers-Guide-to-English#18]

**Comment by yujiangshui** [comment]
对于找学习材料这个问题，我的解决思路是这样的，仅供参考：

1. 不同领域的概念和部分词性会有区别。比如最简单的 git 本意是饭桶，在编程领域是版本控制工具。
2. 英语的知识全集太大了，而且在不断发展，不会有人能了解所有知识。

推导 -》：

1. 先确定你学英语的目的。是为了看懂某个领域（JS？运维？）的技术文章、技术视频？还是为了留学（古典文学？旅游管理？）？
2. 确定之后你就缩小了寻找学习材料的范围了。

比如我的目的是可以出去做技术工作，那么我的领域就是编程方面，尤其是 JS 领域。那么我找一些 JS 等的英文书来看，学习上面的表达方式。泛听材料直接从 YouTube 搜技术关键词就可以了。

但是跟读或者精听需要有字幕，所以我把 Udemy 的视频和字幕下载下来，打算用工具（Mac 可以用 https://www.cibaen.com/，Win 可以用 Aboboo）来做。对于面试方面需求，我是在 YouTube 上搜 interviews 相关视频看。除此之外，还想学些日常交流的段子，所以也下载了《硅谷》无字幕版 + 字幕来看。

不过目前阶段学习重点不在这，所以还没有用到这些资料，只是先提前准备好了。
