### ISSUE TITLE
补充「实践篇」，提供切实可行可操作的计划，方便快速上手

### ISSUE THREAD

**Issue by yujiangshui** [yujiangshui/A-Programmers-Guide-to-English#2]
来自 @imageslr 的提议 https://github.com/yujiangshui/An-English-Guide-for-Programmers/issues/1#issuecomment-452945959

![image](https://user-images.githubusercontent.com/2942913/50948126-2bb2a780-14dc-11e9-80be-b80bae0177db.png)

最好提供多种层次的资料，最好是可交互的页面，有难度和时间选择进行推荐。大家有建议的可以留在这里。

**Comment by zh4ui** [comment]
被楼主的精神感动，不过虽然计划性很强，但是感觉很多方法可能达不到效果。建议看看漏屋的《找对英语学习方法的第1本书》。当然，这本书不会告诉你什么是正确的方法，但是可以帮助你了解什么方法是基本没有效果的。

**Comment by Shellbye** [comment]
读英文原著不错，比如哈利波特系列

**Comment by yujiangshui** [comment]
@zh4ui 谢谢推荐，是这本吗？https://book.douban.com/subject/11522125/ 但看恶魔的奶爸书评并不是很推荐。。。

**Comment by zh4ui** [comment]
对啊。这本书显然不可能帮你学好英文，但是会告诉你怎么做是没有用的。

**Comment by yujiangshui** [comment]
https://github.com/yujiangshui/A-Programmers-Guide-to-English-Practice 已经新开仓库补充实践篇的一些信息（为了避免骚扰 Watch 的朋友）。关于实践和相关活动，请移步该仓库。

**Comment by GreenHatHG** [comment]
> https://github.com/yujiangshui/A-Programmers-Guide-to-English-Practice 已经新开仓库补充实践篇的一些信息（为了避免骚扰 Watch 的朋友）。关于实践和相关活动，请移步该仓库。

这个仓库404啦

**Comment by lcvs** [comment]
你好，你的邮件我已经收到！

**Comment by wangdongdongdong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
