### ISSUE TITLE
能分享关于 PTE 的准备吗

### ISSUE THREAD

**Issue by clinyong** [yujiangshui/A-Programmers-Guide-to-English#21]
江水大大你好，好几个月前看完了你的文档，重新捡起了英语学习的计划。感觉最近在英语学习上面又比较迷茫。想着以雅思，或者 PTE 为目标去学习可能比较好。我个人没有出国的计划，只是想把英语学好。

请问你之前复习 PTE 的时候有报名什么课程吗？方便分享下你复习 PTE 的方法和材料吗？感谢。

**Comment by yujiangshui** [comment]
前段时间忙着出国和适应新工作环境，才看到你的问题，抱歉。

没有出国计划，只想把英语学好，也需要先制定个英语学习目标否则比较难搞（比如能熟读某些技术文档或者看懂无字幕技术视频等）。有了目标之后再去定计划，有时候直接去学 PTE 可能会走一些冤枉路。如果你目标是看懂某个领域的技术文档，应该用这个领域的素材来学习。但是 PTE 偏 academic，主要内容适合留学和学术场景，很可能花了1个月练对你实际目标的效果，还不如花半个月重点积累技术文档的词汇和表达比较好。

**Comment by clinyong** [comment]
感谢回复
