### ISSUE TITLE
资料、工具推荐和扩展阅读 - 2004台湾老师的网站应该被黑了

### ISSUE THREAD

**Issue by JuneSi** [yujiangshui/A-Programmers-Guide-to-English#22]

**Comment by JuneSi** [comment]
点击网站任何地方都会新打开一个网页，会要求下载flash插件，但是打开包内容是病毒。估计时间久被黑了
![1580975027456](https://user-images.githubusercontent.com/20897732/73916458-6e6dcb80-48f8-11ea-9f4a-ec19c9154e77.jpg)
![1580975423498](https://user-images.githubusercontent.com/20897732/73916460-70378f00-48f8-11ea-9693-f17425041b67.jpg)

**Comment by yujiangshui** [comment]
Thanks, I added some tips about this.
