### ISSUE TITLE
www.danci88.com HTTP ERROR 502

### ISSUE THREAD

**Issue by Jason-233** [yujiangshui/A-Programmers-Guide-to-English#31]
单词叭叭？不确定这个工具是不是黄了。是在这里提及的[听写工具](
https://a-programmers-guide-to-english.harryyu.me/training/KnowledgeBase.html#:~:text=%E6%AF%8F%E9%9A%94%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E5%BA%94%E8%AF%A5%E5%AF%BC%E5%87%BA%E4%B8%80%E4%BB%BD%E5%8D%95%E8%AF%8D%E5%88%97%E8%A1%A8%EF%BC%8C%E6%94%BE%E5%9C%A8%20Danci88%20%E4%B8%8A%E9%9D%A2%E8%BF%9B%E8%A1%8C%E5%90%AC%E5%86%99%E3%80%82%E8%BF%99%E4%B8%AA%E5%B7%A5%E5%85%B7%E8%99%BD%E7%84%B6%E6%AF%94%E8%BE%83%E7%AE%80%E9%99%8B%EF%BC%8C%E4%BD%86%E6%98%AF%E9%9D%9E%E5%B8%B8%E5%AE%9E%E7%94%A8%E3%80%82%E9%80%9A%E8%BF%87%E5%90%AC%E5%86%99%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%87%BA%E5%AF%B9%E8%BF%99%E4%B8%AA%E5%8D%95%E8%AF%8D%E7%9A%84%E6%8E%8C%E6%8F%A1%E7%A8%8B%E5%BA%A6%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BD%A0%E8%84%91%E5%AD%90%E7%9E%AC%E9%97%B4%E5%87%BA%E7%8E%B0%E8%BF%99%E4%B8%AA%E5%8D%95%E8%AF%8D%E5%88%99%E8%A1%A8%E7%A4%BA%E6%8E%8C%E6%8F%A1%E4%BA%86%E3%80%82)

**Comment by lcvs** [comment]
你好，你的邮件我已经收到！

**Comment by wangdongdongdong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jason-233** [comment]
https://els.ked.pub/dictation 这个不知道是不是跟原文提到的听写工具差不多。
