### ISSUE TITLE
泥石流

### ISSUE THREAD

**Issue by yobghuiseun** [yujiangshui/A-Programmers-Guide-to-English#34]

**Comment by lcvs** [comment]
你好，你的邮件我已经收到！

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangdongdongdong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by baixian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
