### ISSUE TITLE
建议删去最后的英语流利说

### ISSUE THREAD

**Issue by LuckyJoker** [yujiangshui/A-Programmers-Guide-to-English#8]
《英语流利说》的`懂你英语`看似美好，实则没有太大的作用，并且是收费课程。我觉得会误导初学者，浪费钱财。这个app使用要求极高，需要投入大量的时间，即使你坚持做了也会发现，收益和想象中的不一样。最重要的还是作为收费课程，不能带来和免费学习资源的有效区别。

**Comment by yujiangshui** [comment]
个人赞同 @love-yiyi ，我本身也是流利说老用户，流利说以及懂你英语是偏长期积累的，属于一种微小但轻松的学习方式，它的训练方式也能训练到一定的能力。但如果是备考是非常不推荐的，训练强度和准确性不够。

我再完善一下这个说明，并指向这个问题，留给读者自行判断。

**Comment by yujiangshui** [comment]
已经补充 https://github.com/yujiangshui/A-Programmers-Guide-to-English/commit/c175ddfe5f415eabee459875ca637708c327fe3d

**Comment by weiminghuaa** [comment]
买了半年，不能说真没有用吧，客观点，真的没多大用，跟微小的进步比起来，甚至有些浪费时间

**Comment by yujiangshui** [comment]
争议比较大，删掉了 https://github.com/yujiangshui/A-Programmers-Guide-to-English/commit/7aa7bc3ee181e7eb41f8571fd84bc965727193e6
